FROM php:8.2.12-fpm

COPY ./docker/php/php.ini /usr/local/etc/php/php.ini
COPY ./docker/php/www.conf /usr/local/etc/php-fpm.d/www.conf

RUN ln -snf /usr/share/zoneinfo/Europe/Madrid /etc/localtime \
    && echo "Europe/Madrid" > /etc/timezone

# Instalar dependencias del sistema necesarias

RUN apt-get update \
    && apt-get install -y \
    git \
    unzip \
    libicu-dev \
    libpq-dev \
    zlib1g-dev \
    libzip-dev \
    && docker-php-ext-install \
    intl \
    pdo \
    pdo_pgsql \
    zip \
    bcmath \
    && docker-php-ext-enable opcache \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# RUN apt-get update \
#     && apt-get install -y git acl openssl openssh-client wget zip vim iputils-ping tesseract-ocr tesseract-ocr-spa libtesseract-dev \
#     && apt-get install -y libmagickwand-dev libpng-dev libjpeg-dev zlib1g-dev libzip-dev libxml2-dev libicu-dev libpq-dev librabbitmq-dev libssh-dev \
#     && docker-php-ext-configure gd --enable-gd --with-jpeg \
#     && docker-php-ext-install intl pdo pdo_pgsql zip gd soap bcmath sockets sysvsem \
#     && pecl install xdebug \
#     && pecl install amqp-1.11.0 \
#     && pecl install imagick \
#     && docker-php-ext-enable --ini-name 05-opcache.ini opcache xdebug amqp imagick

# Instalar dependencias PHP con el composer
RUN curl https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer
RUN composer self-update

# Preparamos el espacio donde trabajaremos
RUN mkdir -p /appdata/www

WORKDIR /appdata/www

CMD ["php-fpm", "-F", "-R"]