FROM php:8.2.12-fpm

COPY ./docker/php/php.ini /usr/local/etc/php/php.ini
COPY ./docker/php/www.conf /usr/local/etc/php-fpm.d/www.conf

RUN ln -snf /usr/share/zoneinfo/Europe/Madrid /etc/localtime \
    && echo "Europe/Madrid" > /etc/timezone

# Instalar dependencias del sistema necesarias

RUN apt-get update \
    && apt-get install -y \
    git \
    unzip \
    libicu-dev \
    libpq-dev \
    zlib1g-dev \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libwebp-dev \
    && docker-php-ext-configure gd --with-jpeg --with-webp \
    && docker-php-ext-install \
    intl \
    pdo \
    pdo_pgsql \
    zip \
    bcmath \
    gd \
    && docker-php-ext-enable opcache \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Instalar dependencias PHP con el composer
RUN curl https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer
RUN composer self-update

# Preparamos el espacio donde trabajaremos
RUN mkdir -p /appdata/www

RUN mkdir -p /appdata/uploads \
    && chown -R www-data:www-data /appdata/uploads \
    && chmod -R 775 /appdata/uploads

RUN mkdir -p /appdata/www/var \
    && chown -R www-data:www-data /appdata/www/var \
    && chmod -R 775 /appdata/www/var

WORKDIR /appdata/www

CMD ["php-fpm", "-F", "-R"]