services:
  database:
    image: postgres:16
    env_file:
      - ./docker/.env
    healthcheck:
      test: >
        CMD-SHELL pg_isready -d "$${POSTGRES_DB}" -U "$${POSTGRES_USER}"
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  proxy:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - app
      - media

  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile

  media:
    image: nginx:1.25-alpine
    volumes:
      - ./docker/media/default.conf:/etc/nginx/conf.d/default.conf:ro
      - uploads_data:/usr/share/nginx/html:ro

  api:
    build:
      context: .
      dockerfile: ./docker/api/DockerFile
    # ports:
    #    - "9000:9000"
    volumes:
      - ./symfony:/appdata/www
      - uploads_data:/appdata/www/uploads
    depends_on:
      - database

volumes:
  uploads_data:
  database_data:
