services:
  database:
    image: postgres:16
    env_file:
      - ./docker/.env
    healthcheck:
      test: >
        CMD-SHELL pg_isready -d "$${POSTGRES_DB}" -U "$${POSTGRES_USER}"
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  proxy:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - api
      - app
      - media

  app:
    build: ./app
    volumes:
      - react_build:/usr/share/nginx/html:ro

  media:
    image: nginx:1.25-alpine
    volumes:
      - ./media/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - uploads_data:/usr/share/nginx/html:ro

  api:
    build: ./api
    # environment:
    #   - DB_HOST=database
    #   - DB_USER=${POSTGRES_USER}
    #   - DB_PASS=${POSTGRES_PASSWORD}
    #   - DB_NAME=${POSTGRES_DB}
    volumes:
      - ./api:/var/www/html
      - uploads_data:/var/www/html/public/uploads
    depends_on:
      - database

volumes:
  react_build:
  uploads_data:
  database_data:
