# Etapa 1: Build
FROM node:20-alpine AS builder
WORKDIR /app

# Copiar dependencias e instalar
COPY ./nextjs ./
RUN npm install && npm run build

# Etapa 2: Runtime con Node.js
FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production

# Mejora resolución DNS
RUN echo "hosts: files dns" > /etc/nsswitch.conf

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json
COPY --from=builder /app/next.config.ts ./next.config.ts

RUN npm ci --omit=dev --prefer-offline

CMD ["npm", "start"]