# Etapa 1: Build
FROM node:20-alpine AS builder
WORKDIR /app

# Copiar dependencias e instalar
COPY ./nextjs ./
RUN npm install && npm run build

# Etapa 2: Runtime con Node.js
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copiar solo lo necesario del build
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.js ./next.config.js

RUN npm install --omit=dev

CMD ["npm", "start"]
