doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '16'

    profiling_collect_backtrace: "%kernel.debug%"
    use_savepoints: true
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    identity_generation_preferences:
      Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
    auto_mapping: true
    mappings:
       Category:
          type: attribute
          is_bundle: false
          dir: '%kernel.project_dir%/src/Category/Infrastructure/Persistence'
          prefix: 'App\Category\Infrastructure\Persistence\Entity'
          alias: App\Category\Infrastructure\Persistence\Entity
       Session:
          type: attribute
          is_bundle: false
          dir: '%kernel.project_dir%/src/Authentication/Infrastructure/Persistence'
          prefix: 'App\Authentication\Infrastructure\Persistence\Entity'
          alias: App\Authentication\Infrastructure\Persistence\Entity
       Activity:
          type: attribute
          is_bundle: false
          dir: '%kernel.project_dir%/src/Activity/Infrastructure/Persistence'
          prefix: 'App\Activity\Infrastructure\Persistence\Entity'
          alias: App\Activity\Infrastructure\Persistence\Entity
       UserAndFriend:
          type: attribute
          is_bundle: false
          dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence'
          prefix: 'App\User\Infrastructure\Persistence\Entity'
          alias: App\User\Infrastructure\Persistence\Entity
    controller_resolver:
      auto_mapping: false

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
