# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    jwt.secret: '%env(JWT_SECRET)%'
    jwt.ttl: '%env(int:JWT_TTL)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # Le ponemos los parametros para la inyección
    
    App\Authentication\Infrastructure\Security\FirebaseJwtTokenManager:
        arguments:
            $secretKey: '%jwt.secret%'
            $ttlSeconds: '%jwt.ttl%'

    App\Authentication\Infrastructure\Listener\JwtRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }
    App\Authentication\Infrastructure\Listener\SessionVerificator:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 8 }

    App\Shared\Infrastructure\Listener\OnKernelException:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 8 }
    # please note that last definitions always *replace* previous ones